### ISSUE TITLE
PyTorch+ROCm for AMD Linux maybe?

### ISSUE THREAD

**Issue by reaperx7** [occ-ai/obs-backgroundremoval#535]
Is there anyway we can get PyTorch with ROCm support added for AMD GPUs as an experimental alternative to Tensor-RT to help reduce CPU usage for AMD GPUs?

Many thanks.

**Comment by umireon** [comment]
@royshil

**Comment by royshil** [comment]
rocm in general is supported by ONNX runtime: https://onnxruntime.ai/docs/execution-providers/ROCm-ExecutionProvider.html
i just don't have a solid way of testing this
also we would need to build onnxruntime with rocm support: https://onnxruntime.ai/docs/build/eps.html#amd-rocm 
since the linux release for ORT doesn't include the rocm EP
<img width="290" alt="image" src="https://github.com/occ-ai/obs-backgroundremoval/assets/441170/293018cb-f934-4ed2-9cd4-83d038b513da">
only CUDA and TRT
so i'm not sure... we could certainly use some help w this

**Comment by umireon** [comment]
@royshil We can provide build instructions with ROCm rather than provide pre-built binaries.

@reaperx7 Are you so kind as to develop a ROCm-enabled version of our plugin? We will appreciate your contributions!

**Comment by reaperx7** [comment]
I would if I could, but I can't read code worth a penny.

**Comment by umireon** [comment]
@reaperx7 Do you have an environment to test our ROCm-enabled plugin if we provide you with build instructions?

**Comment by reaperx7** [comment]
I have an up to date ArchLinux system with the ROCm libraries, amdgpu-pro installed, and an RX 5700XT. If it's buildable, and all I need to do is drag and drop it into the plugin folder for OBS, then... Yes.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by payom** [comment]
Just dropping by to mention that I was able to build the plugin using the C/C++ API of the ROCm Execution Provider. All I needed to do was to modify `ort-session-utils.cpp` to add the ROCm EP to the ONNX Runtime session instead of the TensorRT EP, and to then to set the appropriate flag in CMake to use the system's own ONNX Runtime presumably built for ROCm.

**Comment by umireon** [comment]
@reaperx7 @payom I have implemented the initial ROCm support. Can you test this?
https://github.com/occ-ai/obs-backgroundremoval/pull/545

**Comment by reaperx7** [comment]
I can try and test it if a tarball is available.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by umireon** [comment]
@reaperx7 You must build the binary by yourself. We will not provide any pre-built thing.

**Comment by reaperx7** [comment]
That's fine. I just need the sources either in tarball or the exact git repository.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by reaperx7** [comment]
Tried enabling plugin and got error and obs crashed. log file attached.
[error.log](https://github.com/occ-ai/obs-backgroundremoval/files/14234717/error.log)
