### ISSUE TITLE
It doesn't show up in any Filter.

### ISSUE THREAD

**Issue by RogenLothena** [occ-ai/obs-backgroundremoval#547]
**It does not appear in the filter list.**

I installed BackGroundRemoval properly but it doesn't show up in my camera's filters.

//
Everything should appear to be working properly, but it's not.
![image](https://github.com/occ-ai/obs-backgroundremoval/assets/124136916/c18cedc9-3ec1-461a-85f2-ee244cd50c6f)
![image](https://github.com/occ-ai/obs-backgroundremoval/assets/124136916/5c96fd71-ec47-494b-bc3b-c751297b3e1f)

//
Sorry for the language, but as you can see there is nothing related to BackGround Removal.
**[Log and Crash Report](https://obsproject.com/logs/PWA8PLuYxtVEiHJB)**
[Crash 2023-09-11 17-35-13.txt](https://github.com/occ-ai/obs-backgroundremoval/files/14324286/Crash.2023-09-11.17-35-13.txt)
[Crash 2023-10-31 22-05-57.txt](https://github.com/occ-ai/obs-backgroundremoval/files/14324288/Crash.2023-10-31.22-05-57.txt)
[Crash 2024-02-11 07-21-03.txt](https://github.com/occ-ai/obs-backgroundremoval/files/14324289/Crash.2024-02-11.07-21-03.txt)
[Crash 2023-01-27 15-04-25.txt](https://github.com/occ-ai/obs-backgroundremoval/files/14324290/Crash.2023-01-27.15-04-25.txt)
[Crash 2023-03-12 21-05-16.txt](https://github.com/occ-ai/obs-backgroundremoval/files/14324291/Crash.2023-03-12.21-05-16.txt)
[Crash 2023-06-07 11-52-10.txt](https://github.com/occ-ai/obs-backgroundremoval/files/14324292/Crash.2023-06-07.11-52-10.txt)
[Crash 2023-08-20 21-20-52.txt](https://github.com/occ-ai/obs-backgroundremoval/files/14324293/Crash.2023-08-20.21-20-52.txt)
[Crash 2023-08-23 21-48-15.txt](https://github.com/occ-ai/obs-backgroundremoval/files/14324294/Crash.2023-08-23.21-48-15.txt)

**Desktop**

 - OS: \[Windows 10\]
 - Browser: \[Opera, Chrome, Firefox, Edge\]
 - Plugin Version: \[Latest version\]
 - OBS Version: \[28.0.2\]

**Additional context**

Nothing about the problem or an error comes up. It's like the plugin loads but doesn't show up in the filters. I open obs the same way I always open obs and there is no slowness or problem.

**Not**
I should add that my obs-studio file was in Program Files (x86), not Program Files, but I don't think that would have prevented the problem.

**Comment by umireon** [comment]
Can you post here the log not Crash reports?

**Comment by RogenLothena** [comment]
> Collaborator

https://obsproject.com/logs/PWA8PLuYxtVEiHJB This one is Logs

**Comment by LeonardoCT** [comment]
i'm having the same issue, i tryed both manual installation and the exe file, but the plugin won't appear in the options

**Comment by royshil** [comment]
> i'm having the same issue, i tryed both manual installation and the exe file, but the plugin won't appear in the options

the plugin `.dll` should be installed in `C:\Program Files\obs-studio\obs-plugins\64bit`
you should see the `.dll` file there, otherwise OBS will not attempt to load it

**Comment by RogenLothena** [comment]
> > i'm having the same issue, i tryed both manual installation and the exe file, but the plugin won't appear in the options
> 
> the plugin `.dll` should be installed in `C:\Program Files\obs-studio\obs-plugins\64bit` you should see the `.dll` file there, otherwise OBS will not attempt to load it

![image](https://github.com/occ-ai/obs-backgroundremoval/assets/124136916/203c081f-1013-469b-af6b-ef2eb7fb97b4)

**Comment by amcrjlnv** [comment]
I am running on Ubuntu 22.04 and I also do not get any filter to show up, despite the plugin claiming to be loaded in the logs. Interesting, the use of this plugin also causes OBS to detect a memory leak upon exit.
[log.txt](https://github.com/occ-ai/obs-backgroundremoval/files/14490929/log.txt)

I think it's possible that the issue is related to the following lines:
```
warning: obs_register_source: Tried to register obs_source_info with size 408 which is more than libobs currently supports (392)
warning: obs_register_source: Tried to register obs_source_info with size 408 which is more than libobs currently supports (392)
info: [obs-backgroundremoval] Plugin loaded successfully (version 1.1.10)
```
These lines do not show up when I do not have the plugin installed.

**Comment by royshil** [comment]
> > > i'm having the same issue, i tryed both manual installation and the exe file, but the plugin won't appear in the options
> 
> > 
> 
> > the plugin `.dll` should be installed in `C:\Program Files\obs-studio\obs-plugins\64bit` you should see the `.dll` file there, otherwise OBS will not attempt to load it
> 
> 
> 
> ![image](https://github.com/occ-ai/obs-backgroundremoval/assets/124136916/203c081f-1013-469b-af6b-ef2eb7fb97b4)
> 
> 

@RogenLothena Yep that's not going to work since your OBS is in "Program Files (x86)" which is not supported. The plugin works for OBS 64bit. Really OBS also works on 64bit, the x86 version is legacy.
You can reinstall OBS and make sure it is the 64bit version. 
Don't worry about your OBS setup since it will transfer to the new version. (It should do that at least)

**Comment by amcrjlnv** [comment]
> @amcrjlnv Ubuntu is a different issue and in this case I suspect the version of OBS because this difference in struct size suggested it's simply not a compatible version. What version of OBS are you running and how did you install it?

@royshil 
I believe am using the PPA (version 30.0.1), as per the installation instructions.

And looking at the source, you're right. It is a version issue and it's unrelated to this one. There is nothing wrong with the declarations here:
````
extern struct obs_source_info background_removal_filter_info;
extern struct obs_source_info enhance_filter_info;

bool obs_module_load(void)
{
	obs_register_source(&background_removal_filter_info);
	obs_register_source(&enhance_filter_info);
	obs_log(LOG_INFO, "Plugin loaded successfully (version %s)",
		PLUGIN_VERSION);
````

So I think the problem is because 8 months ago one line was added to [obs-source.h](https://github.com/obsproject/obs-studio/blame/release/30.0/libobs/obs-source.h):
![image](https://github.com/occ-ai/obs-backgroundremoval/assets/131231759/76359245-50d5-4fb8-953a-2643f3794deb)
I imagine the other added 8 bytes was due to clang's alignment requirement.

Though, I am still confused, because the 30.0.1 version should have the latest version of the struct. It could also be because of the different compilers use. I'll try to troubleshoot it more when I get back to my computer, but for now I'll mark my previous comment as off topic.

**Comment by RogenLothena** [comment]
> Yep that's not going to work since your OBS is in "Program Files (x86)" which is not supported. The plugin works for OBS 64bit. Really OBS also works on 64bit, the x86 version is legacy. You can reinstall OBS and make sure it is the 64bit version. Don't worry about your OBS setup since it will transfer to the new version. (It should do that at least)

But OBS is already 64bit, I can't change my folder to x86. In general, programs are already installed on x86.

**Comment by RogenLothena** [comment]
> @RogenLothena You can reinstall OBS from the official website and it should install to the 64bit folder. All your OBS setup will remain because it's not in the program files folder.

There are no x64 related files on my computer. I only have Program Files and Program Files (x86). I have also now deleted OBS and reinstalled it to the latest version and I have also downloaded this plugin again and placed it properly in the OBS folder. But it still doesn't work.

**Comment by RogenLothena** [comment]
I solved the problem using the pre-installed exe file, thank you for those who tried to help, it took a really long time to solve this problem. Don't do it manually, use the auto-install exe file and delete and reinstall OBS. Don't forget to back up so you don't lose your settings.
